version: "3"

services:
  script:
    build: script/
    command: python /script/main.py --teamwork-domain netping.teamwork.com --teamwork-token xxxxxxxxxxxxxxxx --confluence-domain netping.atlassian.net --confluence-login xxxxxxxxxxxx --confluence-token xxxxxxxxxxx --host 0.0.0.0 --port 8080 --log-level 20
    ports:
      - "8430:8080"
    restart: always
